mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

snack:
  mvc:
    validation:
      fail-fast: false
  oauth2:
    client:
      server-url: ${OAUTH_SERVER_URL:http://localhost:${server.port:8080}}
      login-page: http://localhost:8000/user/login
      default-success-url: http://localhost:8000/

spring:
  security:
    oauth2:
      client:
        registration:
          snack-upms-server:
            provider: snack-oauth
            client-id: snack-upms-server
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile
        provider:
          snack-oauth:
            authorization-uri: ${snack.oauth2.client.server-url}/oauth2/authorize
            token-uri: ${snack.oauth2.client.server-url}/oauth2/token
            jwk-set-uri: ${snack.oauth2.client.server-url}/oauth2/jwks
            user-info-uri: ${snack.oauth2.client.server-url}/userinfo
            user-name-attribute: sub
      resourceserver:
        jwt:
          jwk-set-uri: ${snack.oauth2.client.server-url}/oauth2/jwks
