services:
  mysql:
    image: mysql:8.4.7
    container_name: snack-mysql-dev
    restart: always
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: snack_dev
    ports:
      - "3306:3306"
    volumes:
      - /Users/jax/docker/mysql/data:/var/lib/mysql
      - /Users/jax/docker/mysql/config:/etc/mysql/conf.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 5s
      timeout: 3s
      retries: 10
