spring:
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=10m,maximumSize=10000
  messages:
    basename: i18n/messages,org.springframework.security.messages

snack:
  oauth:
    security:
      rsa:
        keys:
          - key-id: snack-jwt-key-v1
            private-key: ${SNACK_JWT_PRIVATE_KEY}
            public-key: ${SNACK_JWT_PUBLIC_KEY}
            active: true
  security:
    policy:
      login-page: ${OAUTH_LOGIN_PAGE:/user/login}
      pre-auth-pages:
        pre_auth_reset: /account/change-password
        pre_auth_mfa: /account/verify-mfa
  mfa:
    type: TOTP

---
spring:
  config:
    activate:
      on-profile: dev
snack:
  oauth:
    security:
      rsa:
        keys:
          - key-id: snack-jwt-key-v1
            private-key: |
              -----BEGIN PRIVATE KEY-----
              MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC9WZiUQwRqwfFY
              ro+4CtWhXp6bv0K03CzDtxFXXfT59RaVElUYc3S56nzb1X0XnR432OutrwDY5OR9
              KWBgMNoPz9paXDsSK06QN33wgWvco0XBSbynpzMRKoRYlakkQRbanMzaCqSgi1yO
              Ne9RhcJRswwXrHjIHWX4VbOsdWEbH6E8FxcytRpmIg9xatuobu4WyGzpdmVlq66O
              aHdI3mdQuSS67YKR3KwldaBezwO/SBnD6Gw3z+EGfviUQ7cJ+H/FPMt04o4DucQb
              x9BwNMl5y5EY7JH7hWpkM6TTmBpYp/ePSn79u3viv6C9x1GNv+91dnpmNlPkyyfP
              XPv+KWmVAgMBAAECggEAALwetltQ3NKRFzFbgpD/pwUaaxF0s+6Tc864u570S5fz
              hRktLvVb7lxTT9xHcvrOmOt6niBq5s9+9lSR7+K4pkp4Dk9PRxsRsXZclD0pzFco
              37YjhlyWUokHI1L2o7IVm7CKxrWUXWPGhe4hJ7TFWFtqaoe9kuUP8wrYGqRw+evx
              Lj3v8BsYauZm5KWwX10ddxH+fT5TdiKqqSy72HJG40Q8XyM3KAAdMmEzlIG5VyxT
              XXY4FfsjZhdawSTeLoNIwgNRoWnPNZ5/qdLVilWzE6nyTUmTkwSnzoAhhYTL3ajA
              G+NWcQueY6kfzoqPCkurCF5wDhQMlx2lN1mtOXfk2QKBgQDc44GKeJNJlvHBrPPk
              pXcOpexqlX9P9aDk/lBLxFMPM7y1QaRjD45SEa01BsGJWCIgG5FIZBTKoV6P2aRZ
              OIXWtbFS1KucP4WHGPZjSnF1fkOHjJmDxR1fEybNjScJQxNtWn9/b+XEI8MofsDJ
              HgYkrPfx+/weoIM369gulZJZqQKBgQDbcrQovZNee2rMfn9RRWlHaBIMv7Y7Mr55
              SsvQYiF1zsO/gWMuEbzwg1W3VS88bBrvAXKFDXLr+0c5WvLDWGzIjv+mGPGH5ttb
              aJInAFNw/S2Hyp9exr+a4vHHo0VUnKJ5x4wlziVYNhAD6u7joKzy5HpayPbmENNT
              m4Xe8gV8DQKBgC4vZ5uTYICHjh8H0asiKcWnTcpvXcJTQoP+5L0i3JcWI0Pm6L9J
              tmFUjtnCgt77zY7XFMaFHo/Ls+DyCdoZ5mohbWU7UHKIGZxIzOOv4g9GCkqiTErw
              ARcrAvcBp4LZQouf237C39DmBV1HO3oRzAkJHYK8RFgHCci8iGQdJA+ZAoGBAJv8
              FINA/ZeTMn7ZC7bBF+xh1TKqsuWxVCLzP5yHpDERH6LoXY9JnHt5X1xJeKICVcK9
              zKE2xhFnM2FZfGXOXMTSoHV4FXb8ab+3vOtsF+OgktSK+m1r6JY36pR1Qbq6++KE
              LOJSfckN5KRkQhobA9RDA5W0c4tlOlGborSuY6ehAoGBANGGxgifcNWSRdeQ3TUR
              iE6PLCY2vJZGMawDXMnrDZXQRnA4ZL+X79naFedVliZUUsu5iHZtFNR0UExhKexL
              6JucR5Q1h3UUhXnYMg0zSMwODPZOaRGpH586br+ZrFTHIK00lfyH3+C7jAL/msne
              218i1iwK13FoKeEKys0aZK/p
              -----END PRIVATE KEY-----
            public-key: |
              -----BEGIN PUBLIC KEY-----
              MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvVmYlEMEasHxWK6PuArV
              oV6em79CtNwsw7cRV130+fUWlRJVGHN0uep829V9F50eN9jrra8A2OTkfSlgYDDa
              D8/aWlw7EitOkDd98IFr3KNFwUm8p6czESqEWJWpJEEW2pzM2gqkoItcjjXvUYXC
              UbMMF6x4yB1l+FWzrHVhGx+hPBcXMrUaZiIPcWrbqG7uFshs6XZlZauujmh3SN5n
              ULkkuu2CkdysJXWgXs8Dv0gZw+hsN8/hBn74lEO3Cfh/xTzLdOKOA7nEG8fQcDTJ
              ecuRGOyR+4VqZDOk05gaWKf3j0p+/bt74r+gvcdRjb/vdXZ6ZjZT5Msnz1z7/ilp
              lQIDAQAB
              -----END PUBLIC KEY-----
            active: true
  security:
    policy:
      login-page: http://localhost:8000/user/login
